package com.toedter.calendar;

import java.util.Locale;

import junit.framework.TestCase;

/**
 * Generated by JUnitDoclet, a tool provided by ObjectFab GmbH under LGPL.
 * Please see www.junitdoclet.org, www.gnu.org and www.objectfab.de for
 * informations about the tool, the licence and the authors.
 */

public class JMonthChooserTest
// JUnitDoclet begin extends_implements
		extends TestCase
// JUnitDoclet end extends_implements
{
	// JUnitDoclet begin class
	com.toedter.calendar.JMonthChooser jmonthchooser = null;

	// JUnitDoclet end class

	public JMonthChooserTest(String name) {
		// JUnitDoclet begin method JMonthChooserTest
		super(name);
		// JUnitDoclet end method JMonthChooserTest
	}

	public com.toedter.calendar.JMonthChooser createInstance() throws Exception {
		// JUnitDoclet begin method testcase.createInstance
		return new com.toedter.calendar.JMonthChooser();
		// JUnitDoclet end method testcase.createInstance
	}

	protected void setUp() throws Exception {
		// JUnitDoclet begin method testcase.setUp
		super.setUp();
		jmonthchooser = createInstance();
		// JUnitDoclet end method testcase.setUp
	}

	protected void tearDown() throws Exception {
		// JUnitDoclet begin method testcase.tearDown
		jmonthchooser = null;
		super.tearDown();
		// JUnitDoclet end method testcase.tearDown
	}

	public void testInitNames() throws Exception {
		// JUnitDoclet begin method initNames
		// JUnitDoclet end method initNames
	}

	public void testStateChanged() throws Exception {
		// JUnitDoclet begin method stateChanged
		// JUnitDoclet end method stateChanged
	}

	public void testItemStateChanged() throws Exception {
		// JUnitDoclet begin method itemStateChanged
		// JUnitDoclet end method itemStateChanged
	}

	public void testSetGetMonth() throws Exception {
		// JUnitDoclet begin method setMonth getMonth
		int[] tests = { Integer.MIN_VALUE, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, Integer.MAX_VALUE };

		for (int i = 0; i < tests.length; i++) {
			jmonthchooser.setMonth(tests[i]);
			if (tests[i] < 0) {
				assertEquals(0, jmonthchooser.getMonth());
			} else if (tests[i] > 11) {
				assertEquals(11, jmonthchooser.getMonth());
			} else {
				assertEquals(tests[i], jmonthchooser.getMonth());
			}
		}
		// JUnitDoclet end method setMonth getMonth
	}

	public void testSetDayChooser() throws Exception {
		// JUnitDoclet begin method setDayChooser
		// JUnitDoclet end method setDayChooser
	}

	public void testSetYearChooser() throws Exception {
		// JUnitDoclet begin method setYearChooser
		// JUnitDoclet end method setYearChooser
	}

	public void testSetGetLocale() throws Exception {
		// JUnitDoclet begin method setLocale getLocale
		Locale[] tests = { Locale.getDefault() };

		for (int i = 0; i < tests.length; i++) {
			jmonthchooser.setLocale(tests[i]);
			assertEquals(tests[i], jmonthchooser.getLocale());
		}

		try {
			jmonthchooser.setLocale(null);
			fail("NullPointerException expected.");
		} catch (Exception e) {
			assertTrue(e instanceof NullPointerException);
		}
		// JUnitDoclet end method setLocale getLocale
	}

	public void testSetEnabled() throws Exception {
		// JUnitDoclet begin method setEnabled
		// JUnitDoclet end method setEnabled
	}

	public void testGetComboBox() throws Exception {
		// JUnitDoclet begin method getComboBox
		// JUnitDoclet end method getComboBox
	}

	public void testGetSpinner() throws Exception {
		// JUnitDoclet begin method getSpinner
		// JUnitDoclet end method getSpinner
	}

	public void testHasSpinner() throws Exception {
		// JUnitDoclet begin method hasSpinner
		// JUnitDoclet end method hasSpinner
	}

	public void testMain() throws Exception {
		// JUnitDoclet begin method main
		// JUnitDoclet end method main
	}

	/**
	 * JUnitDoclet moves marker to this method, if there is not match for them
	 * in the regenerated code and if the marker is not empty. This way, no test
	 * gets lost when regenerating after renaming. Method testVault is supposed
	 * to be empty.
	 */
	public void testVault() throws Exception {
		// JUnitDoclet begin method testcase.testVault
		// JUnitDoclet end method testcase.testVault
	}

	public static void main(String[] args) {
		// JUnitDoclet begin method testcase.main
		junit.textui.TestRunner.run(JMonthChooserTest.class);
		// JUnitDoclet end method testcase.main
	}
}
